# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NCKU_MW_GUI_v4.2/medical_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dentist_app(object):
    def setupUi(self, Dentist_app):
        Dentist_app.setObjectName("Dentist_app")
        Dentist_app.resize(1750, 1075)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dentist_app.sizePolicy().hasHeightForWidth())
        Dentist_app.setSizePolicy(sizePolicy)
        Dentist_app.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        Dentist_app.setFont(font)
        Dentist_app.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Dentist_app.setStyleSheet("font:  \"Times New Roman\";\n"
"color: rgb(15, 15, 15);\n"
"background-color: rgb(200, 200, 200);\n"
"")
        self.slider_zoom_1 = QtWidgets.QSlider(Dentist_app)
        self.slider_zoom_1.setGeometry(QtCore.QRect(589, 990, 451, 51))
        self.slider_zoom_1.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 2px solid #cccccc; /* 淺灰色邊框 */\n"
"    height: 4px; /* 增加高度以便顯示更清晰 */\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #007ad9; /* 藍色手柄 */\n"
"    width: 12px; /* 手柄的寬度 */\n"
"    height: 20px; /* 增加手柄的高度，讓手柄變長 */\n"
"    margin: -10px -6px; /* 調整手柄的位置 */\n"
"    border-radius: 4px; /* 圓角更明顯 */\n"
"    border: 1px solid #007ad9; /* 藍色邊框 */\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #cce0ff, stop:1 #007ad9); /* 藍色漸變 */\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #e6f0ff; /* 藍灰色背景 */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #0056a0; /* 更深藍色手柄 */\n"
"    border-color: #0056a0; /* 同樣顏色的邊框 */\n"
"}\n"
"")
        self.slider_zoom_1.setProperty("value", 49)
        self.slider_zoom_1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_zoom_1.setObjectName("slider_zoom_1")
        self.label_ratio_1 = QtWidgets.QLabel(Dentist_app)
        self.label_ratio_1.setGeometry(QtCore.QRect(1070, 990, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_ratio_1.setFont(font)
        self.label_ratio_1.setObjectName("label_ratio_1")
        self.label_img_path = QtWidgets.QLabel(Dentist_app)
        self.label_img_path.setGeometry(QtCore.QRect(460, 30, 1271, 81))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_img_path.setFont(font)
        self.label_img_path.setStyleSheet("QLabel {\n"
"    border: 2px solid #b0bec5; /* 中灰藍色邊框 */\n"
"    padding: 5px;\n"
"    background: #e8f0f8; /* 淺藍灰色背景 */\n"
"    color: #1a3a6c; /* 深藍色文字 */\n"
"    border-radius: 16px; /* 圓角邊框 */\n"
"}\n"
"")
        self.label_img_path.setObjectName("label_img_path")
        self.slider_zoom_2 = QtWidgets.QSlider(Dentist_app)
        self.slider_zoom_2.setGeometry(QtCore.QRect(1340, 990, 281, 51))
        self.slider_zoom_2.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 2px solid #cccccc; /* 淺灰色邊框 */\n"
"    height: 4px; /* 增加高度以便顯示更清晰 */\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #007ad9; /* 藍色手柄 */\n"
"    width: 12px; /* 手柄的寬度 */\n"
"    height: 20px; /* 增加手柄的高度，讓手柄變長 */\n"
"    margin: -10px -6px; /* 調整手柄的位置 */\n"
"    border-radius: 4px; /* 圓角更明顯 */\n"
"    border: 1px solid #007ad9; /* 藍色邊框 */\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #cce0ff, stop:1 #007ad9); /* 藍色漸變 */\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #e6f0ff; /* 藍灰色背景 */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #0056a0; /* 更深藍色手柄 */\n"
"    border-color: #0056a0; /* 同樣顏色的邊框 */\n"
"}\n"
"")
        self.slider_zoom_2.setProperty("value", 49)
        self.slider_zoom_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_zoom_2.setObjectName("slider_zoom_2")
        self.label_ratio_2 = QtWidgets.QLabel(Dentist_app)
        self.label_ratio_2.setGeometry(QtCore.QRect(1660, 990, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_ratio_2.setFont(font)
        self.label_ratio_2.setObjectName("label_ratio_2")
        self.label_zoom_1 = QtWidgets.QLabel(Dentist_app)
        self.label_zoom_1.setGeometry(QtCore.QRect(470, 990, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_zoom_1.setFont(font)
        self.label_zoom_1.setObjectName("label_zoom_1")
        self.label_zoom_2 = QtWidgets.QLabel(Dentist_app)
        self.label_zoom_2.setGeometry(QtCore.QRect(1220, 990, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_zoom_2.setFont(font)
        self.label_zoom_2.setObjectName("label_zoom_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dentist_app)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(450, 140, 711, 811))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    border: 1px solid #2c2c2c; /* 深灰色邊框 */\n"
"    border-radius: 12px; /* 邊角圓滑 */\n"
"    background-color: #1e1e1e; /* 深色背景 */\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 1px solid #2c2c2c; /* 深灰色邊框 */\n"
"    background: #2e2e2e; /* 深灰色背景 */\n"
"    width: 14px; /* 垂直滾動條寬度 */\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 1px solid #2c2c2c; /* 深灰色邊框 */\n"
"    background: #2e2e2e; /* 深灰色背景 */\n"
"    height: 14px; /* 水平滾動條高度 */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #4a4a4a; /* 更深的灰色滾動條手柄 */\n"
"    border-radius: 7px; /* 滾動條手柄圓角 */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #4a4a4a; /* 更深的灰色滾動條手柄 */\n"
"    border-radius: 7px; /* 滾動條手柄圓角 */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: 1px solid #2c2c2c; /* 深灰色邊框 */\n"
"    background: #2e2e2e; /* 深灰色背景 */\n"
"    height: 10px; /* 添加按鈕高度 */\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 1px solid #2c2c2c; /* 深灰色邊框 */\n"
"    background: #2e2e2e; /* 深灰色背景 */\n"
"    height: 10px; /* 減少按鈕高度 */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: 1px solid #2c2c2c; /* 深灰色邊框 */\n"
"    background: #2e2e2e; /* 深灰色背景 */\n"
"    width: 10px; /* 添加按鈕寬度 */\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 1px solid #2c2c2c; /* 深灰色邊框 */\n"
"    background: #2e2e2e; /* 深灰色背景 */\n"
"    width: 10px; /* 減少按鈕寬度 */\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: #1e1e1e; /* 深色背景 */\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: #1e1e1e; /* 深色背景 */\n"
"}\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        # self.scrollAreaWidgetContents = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 707, 807))
        # self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_original_img = QtWidgets.QLabel()
        self.label_original_img.setGeometry(QtCore.QRect(90, 80, 301, 651))
        self.label_original_img.setStyleSheet("QLabel {\n"
"    background-color: #e0e0e0; /* 更深的淺灰色背景 */\n"
"    border: 2px solid #7d7d7d; /* 深灰色邊框 */\n"
"    border-radius: 10px; /* 邊角圓滑 */\n"
"    padding: 5px; /* 內邊距 */\n"
"}\n"
"\n"
"QLabel::image {\n"
"    border-radius: 8px; /* 圖片邊角圓滑 */\n"
"}\n"
"")
        self.label_original_img.setText("")
        self.label_original_img.setObjectName("label_original_img")
        self.scrollArea.setWidget(self.label_original_img)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dentist_app)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1210, 140, 521, 811))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.verticalLayoutWidget_2)
        self.scrollArea_2.setStyleSheet("QScrollArea {\n"
"    border: 1px solid #2c2c2c; /* 深灰色邊框 */\n"
"    border-radius: 12px; /* 邊角圓滑 */\n"
"    background-color: #1e1e1e; /* 深色背景 */\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: 1px solid #2c2c2c; /* 深灰色邊框 */\n"
"    background: #2e2e2e; /* 深灰色背景 */\n"
"    width: 14px; /* 垂直滾動條寬度 */\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: 1px solid #2c2c2c; /* 深灰色邊框 */\n"
"    background: #2e2e2e; /* 深灰色背景 */\n"
"    height: 14px; /* 水平滾動條高度 */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #4a4a4a; /* 更深的灰色滾動條手柄 */\n"
"    border-radius: 7px; /* 滾動條手柄圓角 */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #4a4a4a; /* 更深的灰色滾動條手柄 */\n"
"    border-radius: 7px; /* 滾動條手柄圓角 */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: 1px solid #2c2c2c; /* 深灰色邊框 */\n"
"    background: #2e2e2e; /* 深灰色背景 */\n"
"    height: 10px; /* 添加按鈕高度 */\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 1px solid #2c2c2c; /* 深灰色邊框 */\n"
"    background: #2e2e2e; /* 深灰色背景 */\n"
"    height: 10px; /* 減少按鈕高度 */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: 1px solid #2c2c2c; /* 深灰色邊框 */\n"
"    background: #2e2e2e; /* 深灰色背景 */\n"
"    width: 10px; /* 添加按鈕寬度 */\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 1px solid #2c2c2c; /* 深灰色邊框 */\n"
"    background: #2e2e2e; /* 深灰色背景 */\n"
"    width: 10px; /* 減少按鈕寬度 */\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: #1e1e1e; /* 深色背景 */\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: #1e1e1e; /* 深色背景 */\n"
"}\n"
"")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        # self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 517, 807))
        # self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_crop_tooth = QtWidgets.QLabel()
        self.label_crop_tooth.setGeometry(QtCore.QRect(130, 90, 311, 611))
        self.label_crop_tooth.setStyleSheet("QLabel {\n"
"    background-color: #e0e0e0; /* 更深的淺灰色背景 */\n"
"    border: 2px solid #7d7d7d; /* 深灰色邊框 */\n"
"    border-radius: 10px; /* 邊角圓滑 */\n"
"    padding: 5px; /* 內邊距 */\n"
"}\n"
"\n"
"QLabel::image {\n"
"    border-radius: 8px; /* 圖片邊角圓滑 */\n"
"}\n"
"")
        self.label_crop_tooth.setText("")
        self.label_crop_tooth.setObjectName("label_crop_tooth")
        self.scrollArea_2.setWidget(self.label_crop_tooth)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.layoutWidget_4 = QtWidgets.QWidget(Dentist_app)
        self.layoutWidget_4.setGeometry(QtCore.QRect(50, 560, 361, 91))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_phone = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_phone.setFont(font)
        self.label_phone.setAlignment(QtCore.Qt.AlignCenter)
        self.label_phone.setObjectName("label_phone")
        self.verticalLayout_3.addWidget(self.label_phone)
        self.textEdit_phone = QtWidgets.QTextEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textEdit_phone.setFont(font)
        self.textEdit_phone.setStyleSheet("QTextEdit {\n"
"    border: 2px solid #cce0ff; /* 淺藍色邊框 */\n"
"    padding: 5px;\n"
"    background: #f0f4ff; /* 藍灰色背景 */\n"
"    color: #003366; /* 更深的藍色文字 */\n"
"    border-radius: 10px;\n"
"    selection-background-color: #007ad9; /* 藍色選擇背景 */\n"
"    selection-color: #f0f4ff; /* 藍灰色選擇文字 */\n"
"}\n"
"")
        self.textEdit_phone.setObjectName("textEdit_phone")
        self.verticalLayout_3.addWidget(self.textEdit_phone)
        self.label_status = QtWidgets.QLabel(Dentist_app)
        self.label_status.setGeometry(QtCore.QRect(60, 890, 341, 70))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.layoutWidget = QtWidgets.QWidget(Dentist_app)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 450, 361, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_patient_name = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_patient_name.setFont(font)
        self.label_patient_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_patient_name.setObjectName("label_patient_name")
        self.verticalLayout_14.addWidget(self.label_patient_name)
        self.textEdit_name = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textEdit_name.setFont(font)
        self.textEdit_name.setToolTipDuration(-1)
        self.textEdit_name.setStyleSheet("QTextEdit {\n"
"    border: 2px solid #cce0ff; /* 淺藍色邊框 */\n"
"    padding: 5px;\n"
"    background: #f0f4ff; /* 藍灰色背景 */\n"
"    color: #003366; /* 更深的藍色文字 */\n"
"    border-radius: 10px;\n"
"    selection-background-color: #007ad9; /* 藍色選擇背景 */\n"
"    selection-color: #f0f4ff; /* 藍灰色選擇文字 */\n"
"}\n"
"")
        self.textEdit_name.setObjectName("textEdit_name")
        self.verticalLayout_14.addWidget(self.textEdit_name)
        self.progressBar_status = QtWidgets.QProgressBar(Dentist_app)
        self.progressBar_status.setGeometry(QtCore.QRect(50, 990, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.progressBar_status.setFont(font)
        self.progressBar_status.setStyleSheet("QProgressBar {\n"
"    border: 2px solid #cce0ff; /* 淺藍色邊框 */\n"
"    padding: 2px;\n"
"    text-align: center;\n"
"    background: #f0f4ff; /* 藍灰色背景 */\n"
"    color: #003366; /* 深藍色文字 */\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: #007ad9; /* 藍色填充 */\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.progressBar_status.setProperty("value", 0)
        self.progressBar_status.setObjectName("progressBar_status")
        self.layoutWidget_2 = QtWidgets.QWidget(Dentist_app)
        self.layoutWidget_2.setGeometry(QtCore.QRect(50, 670, 361, 181))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_note = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_note.setFont(font)
        self.label_note.setObjectName("label_note")
        self.verticalLayout_11.addWidget(self.label_note)
        self.textEdit_note = QtWidgets.QTextEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textEdit_note.setFont(font)
        self.textEdit_note.setStyleSheet("QTextEdit {\n"
"    border: 2px solid #cce0ff; /* 淺藍色邊框 */\n"
"    padding: 5px;\n"
"    background: #f0f4ff; /* 藍灰色背景 */\n"
"    color: #003366; /* 更深的藍色文字 */\n"
"    border-radius: 10px;\n"
"    selection-background-color: #007ad9; /* 藍色選擇背景 */\n"
"    selection-color: #f0f4ff; /* 藍灰色選擇文字 */\n"
"}\n"
"")
        self.textEdit_note.setObjectName("textEdit_note")
        self.verticalLayout_11.addWidget(self.textEdit_note)
        self.layoutWidget_3 = QtWidgets.QWidget(Dentist_app)
        self.layoutWidget_3.setGeometry(QtCore.QRect(50, 340, 361, 91))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_excel_name = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_excel_name.setFont(font)
        self.label_excel_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_excel_name.setObjectName("label_excel_name")
        self.verticalLayout_4.addWidget(self.label_excel_name)
        self.textEdit_excel_name = QtWidgets.QTextEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textEdit_excel_name.setFont(font)
        self.textEdit_excel_name.setStyleSheet("QTextEdit {\n"
"    border: 2px solid #cce0ff; /* 淺藍色邊框 */\n"
"    padding: 5px;\n"
"    background: #f0f4ff; /* 藍灰色背景 */\n"
"    color: #003366; /* 更深的藍色文字 */\n"
"    border-radius: 10px;\n"
"    selection-background-color: #007ad9; /* 藍色選擇背景 */\n"
"    selection-color: #f0f4ff; /* 藍灰色選擇文字 */\n"
"}\n"
"")
        self.textEdit_excel_name.setObjectName("textEdit_excel_name")
        self.verticalLayout_4.addWidget(self.textEdit_excel_name)
        self.btn_select_img = QtWidgets.QPushButton(Dentist_app)
        self.btn_select_img.setGeometry(QtCore.QRect(60, 20, 141, 70))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_select_img.setFont(font)
        self.btn_select_img.setStyleSheet("QPushButton {\n"
"    margin: 6px;\n"
"    background-color: #97CBFF;\n"
"    border: 2px solid #ECF5FF;\n"
"    border-radius: 15px;\n"
"    color: #272727;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #2894FF;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #005BB5;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/select_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/images/select_5.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_select_img.setIcon(icon)
        self.btn_select_img.setIconSize(QtCore.QSize(40, 41))
        self.btn_select_img.setCheckable(True)
        self.btn_select_img.setAutoExclusive(True)
        self.btn_select_img.setObjectName("btn_select_img")
        self.label_CEJ_ALC_color = QtWidgets.QLabel(Dentist_app)
        self.label_CEJ_ALC_color.setGeometry(QtCore.QRect(50, 270, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_CEJ_ALC_color.setFont(font)
        self.label_CEJ_ALC_color.setIndent(0)
        self.label_CEJ_ALC_color.setObjectName("label_CEJ_ALC_color")
        self.comboBox_select_tooth = QtWidgets.QComboBox(Dentist_app)
        self.comboBox_select_tooth.setGeometry(QtCore.QRect(110, 180, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox_select_tooth.setFont(font)
        self.comboBox_select_tooth.setStyleSheet("/* style for the QComboBox */\n"
"#comboBox {\n"
"    border: 1px solid #c0c8d0; /* 淺藍灰色邊框 */\n"
"    border-radius: 4px;\n"
"    padding-left: 10px;\n"
"    background-color: #f0f4f8; /* 藍灰色背景 */\n"
"    color: #003366; /* 深藍色文字 */\n"
"}\n"
"\n"
"/* style for drop down area */\n"
"#comboBox::drop-down {\n"
"    border: 1px solid #c0c8d0; /* 淺藍灰色邊框 */\n"
"    border-top: 0; /* 去除下拉箭頭上方的邊框 */\n"
"}\n"
"\n"
"/* style for drop down arrow */\n"
"#comboBox::down-arrow {\n"
"    image: url(:/images/arrow-down-icon.png);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    background-color: #e0e4e8; /* 淺藍灰色背景 */\n"
"    border: 1px solid #c0c8d0; /* 淺藍灰色邊框 */\n"
"    border-radius: 4px; /* 邊框圓角 */\n"
"}\n"
"\n"
"/* style for QComboBox after open select menu */\n"
"#comboBox::down-arrow:on {\n"
"    background-color: #d0d8e0; /* 當打開選單時的背景色 */\n"
"}\n"
"\n"
"/* style for list menu */\n"
"#comboBox QListView {\n"
"    font-size: 12px;\n"
"    border: 1px solid #c0c8d0; /* 淺藍灰色邊框 */\n"
"    padding: 5px;\n"
"    background-color: #f0f4f8; /* 藍灰色背景 */\n"
"    outline: 0; /* 移除 outline */\n"
"}\n"
"\n"
"/* style for list items */\n"
"#comboBox QListView::item {\n"
"    padding-left: 10px;\n"
"    background-color: #f0f4f8; /* 藍灰色背景 */\n"
"    color: #003366; /* 深藍色文字 */\n"
"}\n"
"\n"
"#comboBox QListView::item:hover {\n"
"    background-color: #c0d4e0; /* 淺藍色背景 */\n"
"    color: #003366; /* 深藍色文字 */\n"
"}\n"
"\n"
"#comboBox QListView::item:selected {\n"
"    background-color: #003366; /* 深藍色背景 */\n"
"    color: #f0f4f8; /* 藍灰色文字 */\n"
"}\n"
"")
        self.comboBox_select_tooth.setIconSize(QtCore.QSize(20, 20))
        self.comboBox_select_tooth.setObjectName("comboBox_select_tooth")
        self.comboBox_select_tooth.addItem("")
        self.pushButton_export = QtWidgets.QPushButton(Dentist_app)
        self.pushButton_export.setGeometry(QtCore.QRect(200, 100, 200, 70))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.pushButton_export.setFont(font)
        self.pushButton_export.setStyleSheet("QPushButton {\n"
"                margin: 6px;\n"
"                background-color: #97CBFF;\n"
"                border: 2px solid #ECF5FF;\n"
"                border-radius: 15px;\n"
"                color: #272727;\n"
"            }\n"
"\n"
"            QPushButton::hover {\n"
"                background-color: #2894FF;\n"
"            }\n"
"\n"
"            QPushButton::pressed {\n"
"                background-color: #005BB5;\n"
"                color: #FFFFFF;\n"
"            }")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/export_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/images/export_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_export.setIcon(icon1)
        self.pushButton_export.setIconSize(QtCore.QSize(38, 34))
        self.pushButton_export.setCheckable(True)
        self.pushButton_export.setAutoExclusive(True)
        self.pushButton_export.setObjectName("pushButton_export")
        self.pushButton_import = QtWidgets.QPushButton(Dentist_app)
        self.pushButton_import.setGeometry(QtCore.QRect(200, 20, 200, 70))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.pushButton_import.setFont(font)
        self.pushButton_import.setStyleSheet("QPushButton {\n"
"    margin: 6px;\n"
"    background-color: #97CBFF;\n"
"    border: 2px solid #ECF5FF;\n"
"    border-radius: 15px;\n"
"    color: #272727;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #2894FF;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color: #005BB5;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/import_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/images/import_4.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_import.setIcon(icon2)
        self.pushButton_import.setIconSize(QtCore.QSize(41, 31))
        self.pushButton_import.setCheckable(True)
        self.pushButton_import.setAutoExclusive(True)
        self.pushButton_import.setObjectName("pushButton_import")
        self.pushButton_save = QtWidgets.QPushButton(Dentist_app)
        self.pushButton_save.setGeometry(QtCore.QRect(60, 100, 141, 70))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_save.setStyleSheet("QPushButton {\n"
"                margin: 6px;\n"
"                background-color: #97CBFF;\n"
"                border: 2px solid #ECF5FF;\n"
"                border-radius: 15px;\n"
"                color: #272727;\n"
"            }\n"
"\n"
"            QPushButton::hover {\n"
"                background-color: #2894FF;\n"
"            }\n"
"\n"
"            QPushButton::pressed {\n"
"                background-color: #005BB5;\n"
"                color: #FFFFFF;\n"
"            }")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/save_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/images/save_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_save.setIcon(icon3)
        self.pushButton_save.setIconSize(QtCore.QSize(40, 32))
        self.pushButton_save.setCheckable(True)
        self.pushButton_save.setAutoExclusive(True)
        self.pushButton_save.setObjectName("pushButton_save")

        self.retranslateUi(Dentist_app)
        QtCore.QMetaObject.connectSlotsByName(Dentist_app)

    def retranslateUi(self, Dentist_app):
        _translate = QtCore.QCoreApplication.translate
        Dentist_app.setWindowTitle(_translate("Dentist_app", "Dental app"))
        self.label_ratio_1.setText(_translate("Dentist_app", "ratio 1"))
        self.label_img_path.setText(_translate("Dentist_app", "Image Path"))
        self.label_ratio_2.setText(_translate("Dentist_app", "ratio 2"))
        self.label_zoom_1.setText(_translate("Dentist_app", "Zoom 1"))
        self.label_zoom_2.setText(_translate("Dentist_app", "Zoom 2"))
        self.label_phone.setText(_translate("Dentist_app", "Phone Number:"))
        self.textEdit_phone.setHtml(_translate("Dentist_app", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14px;\"><br /></p></body></html>"))
        self.label_status.setText(_translate("Dentist_app", "Status:"))
        self.label_patient_name.setText(_translate("Dentist_app", "Patient Name:"))
        self.label_note.setText(_translate("Dentist_app", "Note:"))
        self.textEdit_note.setHtml(_translate("Dentist_app", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14px;\"><br /></p></body></html>"))
        self.label_excel_name.setText(_translate("Dentist_app", "Excel Name:"))
        self.btn_select_img.setText(_translate("Dentist_app", "select"))
        self.label_CEJ_ALC_color.setText(_translate("Dentist_app", "** CEJ Points (Green)、ALC Points (Red) **"))
        self.comboBox_select_tooth.setItemText(0, _translate("Dentist_app", "Tooth 1"))
        self.pushButton_export.setText(_translate("Dentist_app", "Export Excel"))
        self.pushButton_import.setText(_translate("Dentist_app", "Import Excel"))
        self.pushButton_save.setText(_translate("Dentist_app", "save"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dentist_app = QtWidgets.QWidget()
    ui = Ui_Dentist_app()
    ui.setupUi(Dentist_app)
    Dentist_app.show()
    sys.exit(app.exec_())
